2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Configure stats pid to 3824513
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Loading settings from /home/dyw/.config/wandb/settings
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Loading settings from /home/dyw/reinforcement_learning/random-network-distillation-pytorch/wandb/settings
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/home/dyw/reinforcement_learning/random-network-distillation-pytorch/train.py'}
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:_log_setup():507] Logging user logs to ./logs/rnd/wandb/run-20250626_171559-5gdpb28a/logs/debug.log
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:_log_setup():508] Logging internal logs to ./logs/rnd/wandb/run-20250626_171559-5gdpb28a/logs/debug-internal.log
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:init():547] calling init triggers
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Agent': 'RND', 'EnvType': ['atari'], 'EnvID': 'ALE/MontezumaRevenge-v5', 'Device': 'cuda:2', 'MaxStepPerEpisode': 4500, 'ExtCoef': 2.0, 'MaxStep': 10000000, 'LearningRate': 0.0001, 'NumEnv': 64, 'NumStep': 128, 'Gamma': 0.999, 'IsLoadModel': False, 'IsRender': False, 'IntGamma': 0.99, 'Lambda': 0.95, 'StableEps': '1e-8', 'StateStackSize': 4, 'PreProcHeight': 84, 'ProProcWidth': 84, 'UseGAE': True, 'UseGPU': True, 'UseNorm': False, 'UseNoisyNet': False, 'ClipGradNorm': 0.5, 'ClipRange': 5, 'Entropy': 0.001, 'Epoch': 4, 'MiniBatch': 4, 'PPOEps': 0.1, 'IntCoef': 1.0, 'StickyAction': True, 'ActionProb': 0.25, 'UpdateProportion': 0.25, 'LifeDone': False, 'ObsNormStep': 50, 'Filters': [32, 64, 64], 'Kernels': [8, 4, 3], 'Strides': [4, 2, 1], 'FcHiddenSizes': [512], 'ActorHiddenSizes': [], 'CriticHiddenSizes': [], 'RndPredHiddenSizes': [512, 512], 'RndTargetHiddenSizes': [512], 'ModelPath': 'models/MontezumaRevenge.model', 'PredictorPath': 'models/MontezumaRevenge.pred', 'TargetPath': 'models/MontezumaRevenge.target', 'LogPath': './logs/rnd/', 'WandbUserName': '2036105396-nanjing-university', 'ProjectName': 'RND_MontezunmaRevenge'}
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:init():596] starting backend
2025-06-26 17:15:59,474 INFO    MainThread:3824513 [wandb_init.py:init():600] setting up manager
2025-06-26 17:15:59,478 INFO    MainThread:3824513 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2025-06-26 17:15:59,483 INFO    MainThread:3824513 [wandb_init.py:init():606] backend started and connected
2025-06-26 17:15:59,491 INFO    MainThread:3824513 [wandb_init.py:init():700] updated telemetry
2025-06-26 17:15:59,508 INFO    MainThread:3824513 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2025-06-26 17:16:01,447 INFO    MainThread:3824513 [wandb_run.py:_on_init():2177] communicating current version
2025-06-26 17:16:02,007 WARNING MainThread:3824513 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    run._on_init()
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2181, in _on_init
    version_result = version_handle.wait(timeout=30)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1158, in init
    getcaller()
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 836, in getcaller
    src, line, func, stack = logger.findCaller(stack_info=True)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/logging/__init__.py", line 1541, in findCaller
    traceback.print_stack(f, file=sio)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/traceback.py", line 190, in print_stack
    print_list(extract_stack(f, limit=limit), file=file)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/home/dyw/miniconda3/envs/xuance_env/lib/python3.8/traceback.py", line 336, in extract
    limit = getattr(sys, 'tracebacklimit', None)
KeyboardInterrupt
